# Generated by Django 5.0.6 on 2025-03-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerRequest',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('healthy', 'Sog‘lom'), ('unhealthy', 'Nosog‘lom')], default='healthy', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(limit_choices_to={'user_type': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_requests', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(limit_choices_to={'user_type': 'shop'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='all.dealerrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.mahsulot')),
            ],
        ),
    ]
