# Generated by Django 5.1.6 on 2025-03-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_dealerrequest_dealerrequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerrequest',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__ne': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='shop',
            field=models.ForeignKey(limit_choices_to={'user_type__ne': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
