# Generated by Django 5.1.6 on 2025-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_alter_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
