# Generated by Django 5.1.6 on 2025-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_alter_sotuv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('shop', 'Shop'), ('omborchi', 'Omborchi')], max_length=10),
        ),
    ]
