# Generated by Django 5.1.6 on 2025-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombor',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ombor',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
