# Generated by Django 5.1.6 on 2025-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0008_sotuvqaytarish_sotuvqaytarishitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuvqaytarish',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
