# Generated by Django 5.1.6 on 2025-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0009_alter_sotuvqaytarish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuvqaytarish',
            name='sana',
            field=models.DateField(auto_now_add=True),
        ),
    ]
